// ── SNAPSHOT GENERATION REQUIRED ─────────────────────────────────────────────
//
// This file must be generated by the EF Core tooling, not written by hand.
// The snapshot must match EF's internal model exactly so that future migrations
// can calculate the correct diff.
//
// HOW TO GENERATE:
//   From the repository root, run:
//
//     dotnet ef migrations add InitialMultiTenant \
//       --project src/Nexo.Infrastructure \
//       --startup-project src/Nexo.Api \
//       --output-dir Persistence/Migrations
//
// If the migration file already exists and only the snapshot is missing, use:
//
//     dotnet ef database update \
//       --project src/Nexo.Infrastructure \
//       --startup-project src/Nexo.Api
//
// Prerequisites:
//   - .NET 8 SDK
//   - dotnet-ef tool:  dotnet tool install --global dotnet-ef
//   - PostgreSQL running (or the build will fail when EF tries to connect)
//
// DO NOT commit a hand-written snapshot — it will cause incorrect diffs on the
// next migration and is nearly impossible to keep in sync manually.
//
// ─────────────────────────────────────────────────────────────────────────────
